### PR TITLE
# fix enabled 'you receive' input field editable

### PR DESCRIPTION
**Pull request by smartcoder0305**

### CODE REVIEW

**Comment by friedger** [comment]
Where is the value stored? How can it been used in the swap contract call?

**Comment by smartcoder0305** [comment]
To achieve what you are looking for, I need to make it a controlled component.
I wanted to discuss every details with you but we didn't have shared time so I fixed the basic bugs only.
I will make this controlled component and will push again.
In the meantime, please take a look at my other PRs.
Thanks.

**Comment by smartcoder0305** [comment]
> Where is the value stored? How can it been used in the swap contract call?

I made it a controlled component. All values will be stored as states within the component. Thank you.

**Comment by friedger** [comment]
Can we make it so that the values survive a page refresh?

**Pull request merged**
